### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by theaspect** [spacecrio/AAA#11]
1. Форматирование кода и именование (имена классов, полей, методов) не соответствует Java Coding Conventions http://www.oracle.com/technetwork/java/codeconvtoc-136057.html
2. В одном файле должно быть не более 1 класса верхнего уровня. Если хочется засунуть два класс в один файл, то создайте пакет
3. JavaDoc оформляется /** а не /*
4. Ошибка тихо подавляется https://github.com/spacecrio/AAA/blob/master/src/com/triplea/Hasher.java#L26
5. Длина строк не должна превышать 120 символов (вертикальная полоска в идее справа)
6. Коды выходов имеет смысл инкапсулировать внутрь EXIT_CODES https://github.com/spacecrio/AAA/blob/master/src/com/triplea/Main.java#L6-L42 и будет так:
    ```
case EXIT_SUCCESSFULLY:
case WRONG_LOGIN:
case WRONG_PASSWORD:
    System.exit(code.getCode())
    break;
    ```
7. Не хватает простого Long? https://github.com/spacecrio/AAA/blob/master/src/com/triplea/Main.java#L66
8. Передавать в параметрах мутабельный класс – очень плохая идея (если вы хотите из функции вернуть два значения, значит это должно быть две отдельных функции) https://github.com/spacecrio/AAA/blob/master/src/com/triplea/UserManager.java#L42
9. Object.equals имеет смысл использовать только если один или оба сравниваемых объекта могут быть null https://github.com/spacecrio/AAA/blob/master/src/com/triplea/UserManager.java#L52
10. Стоит избегать ситуаций когда у тебя объект частично сконуструирован https://github.com/spacecrio/AAA/blob/master/src/com/triplea/UserManager.java#L67
вместо сеттеров используй либо конструктор либо паттерн билдер

**Comment by AsderYork** [comment]
2. Теперь у каждого класса свой файл. К сожалению, однако, разнесение классов по файлам не помогло сократить зависимость, и даже слегка загрязнило область имен.

4. Теперь программа падает при ошибке. Страшно. С записью стектрейса.

5. Тот единственный комментарий, превысивший указанную длину строк, был разбит на два.

6. Насколько много в этом будет смысла? Откровенно говоря мы просто перенесем кейсы из того метода, где они сейчас, в другой, вместе с тем столкнемся с проблемой того, что сейчас EXIT_CODE - перечисление. Придется делать класс. А значит конструктор. А внутри все равно перечисление. А значит теперь при использовании, вместо return WRONG_LOGIN, придется писать return EXIT_CODE(WRONG_LOGIN), что чуточку сложнее, но самое главное - не принесет никакой выгоды.

7. Long ведь тоже немутабельный, да?

8. Исправлено. Более полное мнение на этот счет читайте в свежих коммитах

10. Исправлено.
