### ISSUE TITLE
Review 3.0

### ISSUE THREAD

**Issue by theaspect** [spacecrio/AAA#23]
1. Именование классов не соответствует спецификации
2. В пакете com.triplea мешанина – разнесите по отдельным пакетам. Например все доменные объекты в пакет com.triplea.domain. DAO классы в пакет com.triplea.dao
3. Класса ResourceData, Main не соответствует стандарту
4. В классе Accounter синглтон неправильно создается, кстати зачем он синглтоном сделан?
5. В класс DBWorker, UserData, WrongRoleException есть неиспользуемые методы: либо удалить, либо написать обоснование зачем они нужны
6. В классе ResourceManager мусор
7. Требования R3.4 не выполнено (миграцию номер 1 менять нельзя)
8. Данные должны заполняться через миграцию, а не через код (в вашем случае номер три)
9. Именование таблиц не консистентно: либо используйте подчеркивание везде, либо нигде (переименование тоже должно быть отдельной миграцией, можно объединить с созданием внешних ключей)

**Comment by AsderYork** [comment]
2. Классы перенесены в соответствующие пакеты
4. Теперь Аккаунтер - не синглтон.
5. Неиспользуемые методы удалены
6. Мусор удален
9. Теперь все имена таблиц с подчеркиванием

**Comment by AsderYork** [comment]
3 - Имена методов и полей в данных классах изменены
7 - Добавлено три внешних ключа и один индекс
8 - Данные заполняются через миграцию

**Comment by AsderYork** [comment]
1 - Имена классов доступа изменены
